elasticsearch:
    container_name: elasticsearch
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    environment:
        - http.host=0.0.0.0
        - xpack.security.enabled=false

graylog:
    container_name: graylog
    restart: always
    image: graylog/graylog:2.5
    ports:
        - 9000:9000
        - 12201:12201
        - 12201:12201/udp
        - 514:514
    links:
        - elasticsearch:elasticsearch
    external_links:
        - mongo:mongo
    environment:
        - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
